### PR TITLE
Added KodaDot to Substrate Users

### PR DESCRIPTION
**Pull request by yangwao**
- [ ] Are the audience and objective of the document clear? E.g. a document
for developers that should teach them about transaction fees.
- [ ] Is the writing:
  - **Clear**: No jargon.
  - **Precise**: No ambiguous meanings.
  - **Concise**: Free of superfluous detail.
- [x] Does it follow our [style guide](#documentation-style)?
- [ ] If this is a new page, does the PR include the appropriate infrastructure, e.g. adding the
page to a sidebar?
- [ ] Build the page (TODO link section with instructions). Does it render properly? E.g. no funny lists
or formatting.
- [ ] Do links go to rustdocs or devhub articles rather than code?
- [ ] If this PR addresses an issue in the queue, have you referenced it in the description?

- [x] Didn't found any building instructions 🙆‍♀️

### CODE REVIEW

**Comment by yangwao** [comment]
Thinking of adding Starmesh as well. I'm on it!

**Comment by yangwao** [comment]
Added Starmesh to Substrate Users as well.

**Comment by jimmychu0807** [comment]
Since it has been over 90 days. I suspect we do not care on this matter. Let me know otherwise.

**Comment by yangwao** [comment]
Hey, https://twitter.com/KodaDot is real and has changed logo. Starmesh is on-hold.

**Comment by jimmychu0807** [comment]
@yangwao very cool. Could you update the PR to remove Starmesh, and then I will merge the PR.

**Comment by yangwao** [comment]
Hello @jimmychu0807 done! 
Updated Kodadot logo.
Removed Starmesh as it's on-hold, not dead.

**Comment by yangwao** [comment]
You may want to add .DS_Store to .gitignore?

**Review by jimmychu0807 — APPROVED** [review]
lgtm, thanks @yangwao

**Comment by yangwao** [comment]
Hey, where this appears? 
https://www.substrate.io/substrate-users/ seems have **other content**.

image

**Pull request merged**
