### PR TITLE
Add Subsocial to Substrate users

### PR DESCRIPTION
**Pull request by siman**
Similar changes as in this PR: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/526

### CODE REVIEW

**Review by JoshOrndorff — APPROVED** [review]

**Comment by maxsupera** [comment]
hey @JoshOrndorff, please make sure you check the pr branch locally to make sure nothing breaks before merging with master. in this case, the image field was pointing to a svg that didnt exist, instead of the png file that is there, which broke that page. i've fixed it and pushed to master...

**Comment by siman** [comment]
OMG, sorry, I will fix this real quick

**Comment by maxsupera** [comment]
> OMG, sorry, I will fix this real quick

@siman its cool ive already fixed it! just for future reference...

thanks!

**Comment by siman** [comment]
@thisisvilla I just uploaded SVG actually :) SVG is better than PNG in some cases.
https://github.com/substrate-developer-hub/substrate-cms/pull/26

**Comment by maxsupera** [comment]
@siman sure either way. im importing and transforming pngs at build time so either works. Ive also just added a conditional, so if there is a break because of a mistype, it wont break the whole page... it just shows the circle without a logo.  :D

**Comment by maxsupera** [comment]
> @thisisvilla I just uploaded SVG actually :) SVG is better than PNG in some cases.
> #26

@siman is this just replacing the file, or did you change the reference to the file in `substrate-users.json` back to .svg as well?

`edit:` ive merged and updated the `substrate-users` files back to svg. in the future, please make sure the file name and extension referenced matches the file. Thanks!

**Comment by maxsupera** [comment]
> @thisisvilla I just uploaded SVG actually :) SVG is better than PNG in some cases.
> #26

in regards to this, i would actually prefer to have png files with transparent backgrounds. i can transform those into anything and they present no security risks. SVG files contain code that can be malicious if not thoroughly checked or sanitized: https://blog.online-convert.com/svg-file-and-its-danger/

**Comment by subsocialdev** [comment]
> SVG files contain code that can be malicious if not thoroughly checked or sanitized

Interesting. So now you have both our SVG and PNG. You can use PNG, no problem.

**Comment by maxsupera** [comment]
@subsocialdev awesome! thanks! 🙌

**Pull request merged**
